
export const data = [
{
 'id': 1,
 'coverImg': "black1.jpg",
 'description': "Black sandals with pointy toe",
 'name': "Teresa",
 'price': 110.99,
},
{'id': 2,
 'coverImg': "black2.jpg",
 'description': "Ladies black sandals with comfortable heel",
 'name': "Beatrice",
 'price': 82.99,
},
{'id': 3,
 'coverImg': "black3.png",
 'description': "Ladies black pumps with short heel",
 'name': "Emilia",
 'price': 94.99,
},
{'id': 4,
 'coverImg': "blue1.jpg",
 'description': "Ladies blue pumps",
 'name': "Cora",
 'price': 119.99,
},
{'id': 5,
 'coverImg': "grey1.jpg",
 'description': "Ladies grey pumps with tall heel",
 'name': "Cleo",
 'price': 114.99,
},
{'id': 6,
 'coverImg': "grey2.jpg",
 'description': "Ladies grey sandals with comfortable heel",
 'name': "Jude",
 'price': 78.99,
},
{'id': 7,
 'coverImg': "pink1.jpg",
 'description': "Comfortable pink shoes with flat sole",
 'name': "Carolyn",
 'price': 52.99,
},
{'id': 8,
 'coverImg': "pink2.jpg",
 'description': "Ladies pink pumps with golden tip",
 'name': "Kristen",
 'price': 75.99,
},
{'id': 9,
 'coverImg': "pink3.png",
 'description': "Ladies pink pumps with comfortable heel",
 'name': "Cassandra",
 'price': 85.99,
},
{'id': 10,
 'coverImg': "red1.jpg",
 'description': "Ladies red pumps",
 'name': "Madison",
 'price': 97.99,
},
{'id': 11,
 'coverImg': "red2.jpg",
 'description': "Red sandals with comfortable heel",
 'name': "Jolie",
 'price': 85.99,
},
{'id': 12,
 'coverImg': "snake1.jpg",
 'description': "Ladies snake leather boots",
 'name': "Willow",
 'price': 165.99,
},
{'id': 13,
 'coverImg': "stamp1.png",
 'description': "Ladies stamped heels with black lace",
 'name': "Priscilla",
 'price': 125.99,
},
{'id': 14,
 'coverImg': "white1.png",
 'description': "Ladies white pumps",
 'name': "Reina",
 'price': 134.99,
},
{'id': 15,
 'coverImg': "white2.jpg",
 'description': "Ladies white pumps with black tip",
 'name': "Arabella",
 'price': 184.99,
},
{'id': 16,
 'coverImg': "yellow1.jpg",
 'description': "Ladies stylish yellow pumps",
 'name': "Margarita",
 'price': 195.99,
},
]

